s="Tops Technologies"

print(s)
print(len(s))
print(s.capitalize())
print(s.casefold())
print(s.lower())
print(s.upper())
print(s.center(30,"#"))
print(s.count("o"))
print(s.endswith("es"))
print(s.startswith("To"))
print(s.find("log"))
print(s.index("log"))
print("tops123".isalnum())
print("tops".isalnum())
print("123".isalnum())
print("tops 123".isalnum())
print("tops".isalpha())
print("123".isnumeric())
print(" ".isspace())
print(s.istitle())
print(s.replace("T","t"))
print(s.swapcase())
